version: '3.7'

services:
  blog:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
    - "8000:8000"
    env_file:
      - ./.env
    depends_on:
       - db

  db:
    image: "postgres:10.3-alpine"
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
