# Generated by Django 3.0.8 on 2020-10-21 04:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
