# Generated by Django 3.0.6 on 2020-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200531_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
